### ISSUE TITLE
Export BuildingSync 2.0 xml results

### ISSUE THREAD

**Issue by macumber** [NREL/bricr#11]
Include fields needed by https://github.com/SEED-platform/seed/issues/1899

**Comment by macumber** [comment]
1.	Under Scenario/ScenarioType/CalculationMethod, added:
a.	WeatherDataType:  This is where to indicate Actual Weather Data vs. Typical Year.  Enums are: CWEC, CZRV2, IWEC, Onsite Measurement, TMY, TMY2, TMY3, Weather Station.   Use TMYs to mean Typical Year, and Weather Station for actual year.
b.	SimulationCompletionStatus:  This should map to the old OpenStudioCompletedStatus UDF.  The old BaselineCompletionStatus UDF I don’t think is needed…you can get that from the “Baseline” Scenario’s SimulationCompletionStatus.  Enums:  'Not Started', 'Started', 'Queued', 'Finished', 'Other', 'Unknown'
 
EXAMPLE:
<Scenario>
   <ScenarioType>
              <PackageOfMeasures>
       <CalculationMethod>
<Modeled>
          <WeatherDataType>Typical Meteorological Year</WeatherDataType>
          <SimulationCompletionStatus>Not Started</SimulationCompletionStatus>
       </Modeled>
</CalculationMethod>
<PackageOfMeasures>
                 </ScenarioType>
              </Scenario>
 
2.	CustomMeasureName, under Measure: maps to the old OpenStudioMeasureName UDF:
 
EXAMPLE:
<Measure>
<CustomMeasureName> TBD</CustomMeasureName>
              </Measure>
 
3.	The old OpenStudioAnnualSiteEnergy_MMBtu UDF maps to: AllResourceTotal/SiteEnergyUse.  Note: This is stored in kBtu, so will need to convert first.
 
EXAMPLE: 
<Scenario>
          <AllResourceTotals>
              <AllResourceTotal>
                     <EndUse>All end uses</EndUse>
                     <SiteEnergyUse>28772000</SiteEnergyUse>
              </AllResourceTotal>
   </AllResourceTotals>
</Scenario>
                
4.	AnnualSavingsElectricity and AnnualSavingsNaturalGas UDFs can be mapped to the existing AnnualSavingsByFuel section:  **I didn’t see these in the BRICR xml example. Maybe for future use?**
 
EXAMPLE:
<Scenario>
   <ScenarioType>
<PackageOfMeasures>
<AnnualSavingsByFuels>
   <AnnualSavingsByFuel>
      <EnergyResource>Electricity</EnergyResource>
      <ResourceUnits>kBtu</ResourceUnits>
      <AnnualSavingsNativeUnits>500</AnnualSavingsNativeUnits>
   </AnnualSavingsByFuel>
   <AnnualSavingsByFuel>
      <EnergyResource>Natural Gas</EnergyResource>
      <ResourceUnits>kBtu</ResourceUnits>
      <AnnualSavingsNativeUnits>500</AnnualSavingsNativeUnits>
   </AnnualSavingsByFuel>
</AnnualSavingsByFuels>
              </PackageOfMeasures>
          </ScenarioType>
      </Scenario>
 
5.	The old OpenStudioAnnualElectricity_kBtu and OpenStudioAnnualNaturalGas_kBtu UDFs  as well as the requested new AnnualPeakElectricityDemand and AnnualPeakNaturalGasDemand can be mapped to the existing (and newly expanded peak fields) under ResourceUse:
 
EXAMPLE:
<Scenario>
    <ResourceUses>
       <ResourceUse>
          <EnergyResource>Electricity</EnergyResource>
          <ResourceUnits>kBtu</ResourceUnits>
          <AnnualFuelUseNativeUnits>27006371</AnnualFuelUseNativeUnits>
          <AnnualFuelUseConsistentUnits>(Whatever it is in MMBtu/yr)</AnnualFuelUseConsistentUnits>
          <PeakResourceUnits>kW</PeakResourceUnits>
          <AnnualPeakNativeUnits>1000</AnnualPeakNativeUnits>
          <AnnualPeakConsistentUnits>(Whatever it is in kW)</AnnualPeakConsistentUnits>
       </ResourceUse>
   </ResourceUses>
</Scenario>
 
6.	Monthly consumption.  Although this is not in the current BRICR file, this could go under Scenario/TimeseriesData.  Must specify a ResourceUse (#5 above), and then can link to it in Timeseries.  Can also do monthly peak numbers this way.  I can work on an example once we have monthly consumption.

**Comment by macumber** [comment]
Can you also update https://github.com/NREL/bricr/blob/develop/geojson_to_buildingsync.rb to write out BuildingSync 2.0 files.  Should be super easy

**Comment by kflemin** [comment]
https://github.com/NREL/bricr/pull/13
