### ISSUE TITLE
Need to update defaults for retail

### ISSUE THREAD

**Issue by macumber** [NREL/bricr#15]
"0.0 value for floor height will be replaced with smart default for RetailStandalone of 20.0.",
 "0.0 value for window to wall ratio will be replaced with smart default for RetailStandalone of 0.07.",

**Comment by macumber** [comment]
Imma to provide the numbers, @sanghlee-lbnl to implement in simulation

**Comment by corymosiman12** [comment]
Sang Hoon updated suggested values to: 4 walls all at 0.15 WWR and 15 foot floor height. See:
72ccb100fb5fefed9bd8b357b4a7689fc68efe12
