### ISSUE TITLE
Run all the BuildingSync files from SEED

### ISSUE THREAD

**Issue by macumber** [NREL/bricr#20]

**Comment by macumber** [comment]
`bundle update`
`bundle exec rake ruby bin/monitor_seed.rb ./config.rb > out.log`

**Comment by corymosiman12** [comment]
hey @sanghlee-lbnl can you confirm that only 'Hotel', 'Retail', and 'Office' are the three property types that can successfully be modeled?

**Comment by sanghlee-lbnl** [comment]
Yes. Correct.
One thing to add: office < 20000 ft2 is a small office and  >=20000 <75000
ft2  is a medium office. Office greater than 75000 won't be modeled.

Thanks,
Sang Hoon

**Comment by corymosiman12** [comment]
Thanks Sang Hoon!

**Comment by corymosiman12** [comment]
This task is at a point of significant completion.  Status update sent by @corymosiman12 on 2019-09-30 to project team provides summary.
